FROM python:3.13-alpine

WORKDIR /app

COPY requirements.txt requirements-test.txt ./

RUN pip install --no-cache-dir -r requirements.txt && \
    pip install --no-cache-dir -r requirements-test.txt

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

COPY --chown=appuser:appgroup . .

RUN chown -R appuser:appgroup /app

USER appuser
